import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/themes/ThemeProvider";
import SidebarDesktop from "@/components/sidebar/SidebarDesktop";
import UserProfile from "@/components/sidebar/UserProfile";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { PanelLeft, Search } from "lucide-react";
import SidebarMobile from "@/components/sidebar/SidebarMobile";
import { Input } from "@/components/ui/input";
import { ToggleButton } from "@/components/themes/ToggleButton";
import Link from "next/link";
import Image from "next/image";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "E-Shop Dashboard",
  description: "Generated by create next app",
};
import logo from "../../asserts/logo1.jpeg";
export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <div className="flex min-h-screen w-full flex-col bg-muted/40 border">
            <SidebarDesktop />
            <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
              <header className="sticky  top-0 z-30 flex h-14 items-center gap-4 border-b  bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
                <Sheet>
                  <SheetTrigger asChild>
                    <Button size="icon" variant="outline" className="sm:hidden">
                      <PanelLeft className="h-5 w-5" />
                      <span className="sr-only">Toggle Menu</span>
                    </Button>
                  </SheetTrigger>
                  <SheetContent side="left" className="sm:max-w-xs">
                    <SidebarMobile />
                  </SheetContent>
                </Sheet>
                <div className="hidden md:block">
                  <Link
                    href="/"
                    className="flex items-center space-x-2 rtl:space-x-reverse"
                  >
                    <Image
                      src={logo}
                      className="rounded-lg"
                      alt="E-shop Logo"
                      height={40}
                      width={40}
                    />
                    <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                      E-Shop
                    </span>
                  </Link>
                </div>
                <div className="relative ml-auto flex items-center gap-4">
                  {/* <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                  <Input
                    type="search"
                    placeholder="Search..."
                    className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[320px]"
                  /> */}
                  <ToggleButton />
                  <UserProfile />
                </div>
              </header>
              <div className="p-4 sm:px-6 sm:py-0 ">{children}</div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
