import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavbarHome from "@/components/shared/NavbarHome";
import FooterHome from "@/components/shared/footer/FooterHome";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <NavbarHome />
        <main className="min-h-screen overflow-hidden">{children}</main>
        <FooterHome />
      </body>
    </html>
  );
}
