import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import NavbarHome from "@/components/shared/NavbarHome";
import FooterHome from "@/components/shared/footer/FooterHome";
import { ThemeProvider } from "@/components/themes/ThemeProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "E-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <NavbarHome />
          <main className="min-h-screen overflow-hidden">{children}</main>
          <FooterHome />
        </ThemeProvider>
      </body>
    </html>
  );
}
